name: Export OpenTelemetry Trace for CI/CD

on:
  workflow_run:
    workflows:
      - CI
      - CD
    types: [completed]
  workflow_dispatch:
    inputs:
      runId:
        description: Workflow Run ID to export
        required: true
        type: string

jobs:
  otel-export-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - name: Export OpenTelemetry Trace
        if: secrets.OTEL_EXPORTER_OTLP_ENDPOINT != ''
        uses: corentinmusard/otel-cicd-action@0f9f16fceb53fd8c996042e28c642ec61f844876 # v4.0.0
        continue-on-error: true
        with:
          otlpEndpoint: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
          otelServiceName: svelte-bun
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id || inputs.runId }}
